apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mlflow
  namespace: infra-tools
spec:
  project: default
  source:
    repoURL: https://github.com/msolonin/mlflow-helm-mlops.git
    targetRevision: main
    path: charts/mlflow
    helm:
      releaseName: mlflow
      # Only include if you have a custom values file
      # valueFiles:
      #   - values-custom.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: mlflow
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
